default: build-module build-wezterm

build-module:
	@echo "compiling: all module"
	@rm -vf events.lua key-tables.lua keybinds.lua launch-menu.lua
	fennel -c events.fnl > events.lua
	fennel -c key-tables.fnl > key-tables.lua
	fennel -c keybinds.fnl > keybinds.lua
	fennel -c launch-menu.fnl > launch-menu.lua

build-wezterm:
	@echo "compiling: wezterm.fnl"
	@rm -vf wezterm.lua
	fennel -c wezterm.fnl > wezterm.lua
