# Starship configurations

# editor completion "not working in helix"
"$schema" = "https://starship.rs/config-schema.json"

# Don't print a new line at the start of the prompt
add_newline = false

[character]
format = "$symbol [ ](fg:#ebbcba)"
success_symbol = "[](bold fg:#31748f)" 
error_symbol = "[](bold fg:#eb6f92)"
vicmd_symbol = "[  ](bold fg:#9ccfd8)"

# Battery Module
[battery]
full_symbol = ""
charging_symbol = ""
discharging_symbol = ""

[[battery.display]] 
threshold = 10
style = "bold #eb6f92"

[[battery.display]]
threshold = 20
style = "bold #f6c177"

# Directory Module
[directory]
style = "bold #eb6f92"
truncation_length = 3
truncation_symbol = "_/"
read_only = "  "
read_only_style = "#9ccfd8"

# Git Module
[git_branch]
style = "bold #f6c177"

[git_commit]
style = "bold #f6c177"

[git_status]
style = "bold #c4a7e7"

[git_metrics]
disabled = false
added_style = "bold #9ccfd8"
deleted_style = "bold #eb6f92"

[git_state]
style = "bold #ebbcba"

[package]
format = "via [ $version](208 bold) "