# -----------------------------------------------------------------------------
# Editor Configurations
# -----------------------------------------------------------------------------

# Theme -----------------------------------------------------------------------
theme="rose_pine_fix"

# Editor ----------------------------------------------------------------------
[editor]
mouse = true
line-number = "relative"
rulers = [80,]
shell = ["nu", "-c"]
gutters = ["diagnostics",]
idle-timeout = 0
true-color = true

# LSP -------------------------------------------------------------------------
[editor.lsp]
display-messages = true

# Cursor ----------------------------------------------------------------------
[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

# Whitespace Render -----------------------------------------------------------
[editor.whitespace]
render = "all"

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
tab = "→"
newline = "⏎"

# -----------------------------------------------------------------------------
# Keymaps
#------------------------------------------------------------------------------

# Normal
[keys.normal]
"C-w" = "no_op"
"["   = "no_op"
"]"   = "no_op"

# Match and Move
[keys.normal.m]
f   = "goto_next_function"
F   = "goto_prev_function"
c   = "goto_next_class"
C   = "goto_prev_class"
p   = "goto_next_parameter"
P   = "goto_prev_parameter"
x   = "goto_next_comment"
X   = "goto_prev_comment"
"." = "goto_next_paragraph"
"," = "goto_prev_paragraph"
o   = "add_newline_below"
O   = "add_newline_above"

# Normal Space Mode -----------------------------------------------------------
[keys.normal."space"]
"." = "file_picker_in_current_directory"
"," = "global_search"
c   = "command_mode"
C   = "command_palette"
q   = ":quit" 
Q   = ":quit!"
F   = "no_op"
h   = "no_op"
p   = "no_op"
P   = "no_op"
y   = "no_op"
Y   = "no_op"
k   = "no_op"
s   = "no_op"
S   = "no_op"
a   = "no_op"
r   = "no_op"
R   = "no_op"
"/" = "no_op"
"?" = "no_op"

# Buffer ----------------------------------------------------------------------
[keys.normal."space".b]
b = "buffer_picker"
n = "goto_next_buffer"
p = "goto_previous_buffer"
d = ":buffer-close"
D = ":buffer-close-others"
x = ":buffer-close-all"

# Editor ----------------------------------------------------------------------
[keys.normal."space".e]
r = ":config-reload"
R = "replace_selections_with_clipboard"
p = "paste_clipboard_after"
P = "paste_clipboard_before"
y = "yank_joined_to_clipboard"
Y = "yank_main_selection_to_clipboard"

# File ------------------------------------------------------------------------
[keys.normal."space".f]
f = "file_picker_in_current_directory"
F = "file_picker"
n = ":new"
s = ":write"
S = ":write-quit"

# LSP
[keys.normal."space".l]
a = "code_action"
d = "goto_definition"
t = "goto_type_definition"
r = "goto_reference"
R = "rename_symbol"
i = "goto_implementation"
h = "hover"
s = "symbol_picker"
S = "workspace_symbol_picker"
p = "goto_prev_diag"
n = "goto_next_diag"
f = "goto_first_diag"
l = "goto_last_diag"

# Open 
[keys.normal."space".o]
b = ":open ~/.config/broot/conf.toml"
c = ":config-open"
e = ":open ~/.config/nushell/env.nu"
g = ":open ~/.config/gitui/key_bindings.ron"
k = ":open ~/.config/kitty/kitty.conf"
n = ":open ~/.config/nushell/config.nu"
s = ":open ~/.config/starship/starship.toml"
t = ":open "
z = ":open ~/.config/zellij/config.yaml"

# Window ----------------------------------------------------------------------
[keys.normal."space".w]
w = "no_op"
C-w = "no_op"
q = "no_op"
C-q = "no_op"
o = "no_op"
C-o = "no_op"
n = "rotate_view"
S = "hsplit_new"
V = "vsplit_new"
d = "wclose"
D = "wonly"

# Insert Mode -----------------------------------------------------------------
[keys.insert]
j = {  k = "normal_mode" }